import { Inter } from "next/font/google";
import "./globals.css";
import LeftMenu from "@/components/LeftMenu";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full bg-white">
      <body className={inter.className}>
        <Providers>
          <div className="h-full">
            <LeftMenu>{children}</LeftMenu>
          </div>
        </Providers>
      </body>
    </html>
  );
}
